site_name: danieelst.github.io
site_description: My blog
site_url: http://danieelst.github.io
header_title: © 2024 Daniel Stribrand

theme:
  name: material
  font: false
  palette:
    - scheme: default
      primary: white
      accent: red
  favicon: false
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css

nav:
  - index.md

plugins:
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      use_git: false
      json_feed_enabled: false
      feeds_filenames:
        rss_created: index.xml
        rss_updated: updated.xml
